### ISSUE TITLE
All i need is something to click send raid on my self created farm list.

### ISSUE THREAD

**Issue by scissors14** [tr0mb1r/tkbotpy#3]
Would love this and donate money , Thanks

**Comment by tr0mb1r** [comment]
I'm gonna make it soon. May be on the weekends.

**Comment by tr0mb1r** [comment]
I'm gonna make it soon. May be on the weekends.

**Comment by tr0mb1r** [comment]
@scissors14 I've made a little function in [https://github.com/tr0mb1r/tkbotpy/commit/3fe55d035d786dac6dee003af4a2931f246544ca](url)

**Comment by scissors14** [comment]
Excuse my lack of anything to do with coding.  Last thing I've done is made some custom pathing and settings on my MMOGlider account.

I downloaded Python3.6.2

https://pypi.python.org/pypi/PyVirtualDisplay
http://www.seleniumhq.org/download/
https://www.crummy.com/software/BeautifulSoup/bs4/download/4.6/

I would go about doing this correct https://docs.python.org/3/installing/index.html
python -m pip install "SomePackage".

Yep, I got a lot way to go. Will let you know if i get it rolling

**Comment by scissors14** [comment]
I got everything, going and it comes to this. Obviously, I haven't configured something right. I'm stuck now. 

RESTART: C:\Users\JWG\AppData\Local\Programs\Python\Python36-32\Scripts\tk_bot.py

**Comment by tr0mb1r** [comment]
What errors do you get?

**Comment by tr0mb1r** [comment]
That's how it works:
# python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
username="username" - set you username
password="password" - set your password
chromedriver="/pew/python/kingdoms_chatbot/chromedriver" - set path/to/chromedriver
base_url="https://www.kingdoms.com/"
from tk_bot import TravianKingdoms
tk.driver_start(chromedriver) - start chrome browser in background mode
tk.get_page(base_url)
tk.login(username,password)
tk.get_data() - it will return next information about your villages
```
[ {
    'LK0': {
        'troops': {
            'unit_8': '0', 'unit_6': '0', 'unit_10': '0', 'unit_9': '0', 'unit_0': '12891', 'unit_3': '0', 'unit_7': '0', 'unit_5': '7', 'unit_1': '2', 'unit_4': '1698', 'unit_2': '1058'
        }
        ,
        'resources': {
            'wood': '36268', 'iron': '53850', 'crop': '71341', 'clay': '36040'
        }
        ,
        'id': '535871538'
    }
}
,
{
    'LK1': {
        'troops': {
            'unit_8': '0', 'unit_6': '10', 'unit_10': '1', 'unit_9': '0', 'unit_0': '0', 'unit_3': '4175', 'unit_7': '0', 'unit_5': '0', 'unit_1': '3545', 'unit_4': '0', 'unit_2': '0'
        }
        ,
        'resources': {
            'wood': '69405', 'iron': '40189', 'crop': '52614', 'clay': '69936'
        }
        ,
        'id': '535740471'
    }
}
,
{
    'LK2': {
        'troops': {
            'unit_8': '0', 'unit_6': '0', 'unit_10': '0', 'unit_9': '0', 'unit_0': '8887', 'unit_3': '0', 'unit_7': '0', 'unit_5': '0', 'unit_1': '0', 'unit_4': '1488', 'unit_2': '0'
        }
        ,
        'resources': {
            'wood': '33376', 'iron': '75751', 'crop': '31935', 'clay': '66326'
        }
        ,
        'id': '536068148'
    }
}
,
{
    'LK3': {
        'troops': {
            'unit_8': '0', 'unit_6': '0', 'unit_10': '0', 'unit_9': '0', 'unit_0': '1457', 'unit_3': '0', 'unit_7': '0', 'unit_5': '0', 'unit_1': '0', 'unit_4': '0', 'unit_2': '0'
        }
        ,
        'resources': {
            'wood': '33609', 'iron': '56944', 'crop': '76633', 'clay': '21030'
        }
        ,
        'id': '536035384'
    }
}
,
{
    'LK4': {
        'troops': {
            'unit_8': '0', 'unit_6': '0', 'unit_10': '0', 'unit_9': '0', 'unit_0': '0', 'unit_3': '0', 'unit_7': '0', 'unit_5': '0', 'unit_1': '0', 'unit_4': '0', 'unit_2': '0'
        }
        ,
        'resources': {
            'wood': '2801', 'iron': '5814', 'crop': '5799', 'clay': '218'
        }
        ,
        'id': '536002618'
    }
}

]
```
tk.farm_list_atk("535740471",0) - will start "Startup farm list" from village with ID 535740471 (LK1)
tk.stop_driver() - will turn off background browser
